<?php

namespace LaracraftTech\LaravelSpyglass\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use LaracraftTech\LaravelSpyglass\EntryType;
use LaracraftTech\LaravelSpyglass\Storage\EntryModel;

class EntryModelFactory extends Factory
{
    /**
     * Get the name of the model that is generated by the factory.
     *
     * @return string
     */
    public function modelName()
    {
        return EntryModel::class;
    }

    /**
     * {@inheritdoc}
     */
    public function definition()
    {
        return [
            'uuid' => $this->faker->uuid,
            'type' => $this->faker->randomElement([
                EntryType::COMMAND,
                EntryType::JOB,
                EntryType::REQUEST,
                EntryType::SCHEDULED_TASK,
            ]),
            'content' => [$this->faker->word => $this->faker->word],
        ];
    }
}
